### PR TITLE
cleanup: remove `ext_` prefix from external helm chart config filenames & use `.` instead of `-` for instance names

### PR DESCRIPTION
**Pull request by lemeurherve**
The `ext_` prefix wasn't particularly useful, and was more annoying than anything else.

### CODE REVIEW

**Review by dduportal — DISMISSED** [review]
LGTM nice job!

Let's deploy this change monday if ok for you?

**Comment by dduportal** [comment]
- File conflicts to be fixed
- Helmfile diff is 👍 Gotta re-check once conflicts fixed
- The updatecli checks, of course, because it runs against `main`: we can ignore this check

**Comment by lemeurherve** [comment]
3 rebase attemps later I give up 😓

**Comment by dduportal** [comment]
Superseeded by https://github.com/jenkins-infra/kubernetes-management/pull/3798

**Pull request closed without merging**
