### PR TITLE
chore: add updatecli manifests for `rating`

### PR DESCRIPTION
**Pull request by lemeurherve**

### CODE REVIEW

**Review by dduportal — CHANGES_REQUESTED** [review]
https://github.com/jenkins-infra/helm-charts/blob/main/updatecli/updatecli.d/rating.yaml

**Comment by lemeurherve** [comment]
I missed that 😅 
Will change plugin-health-scoring manifests accordingly.

**Comment by lemeurherve** [comment]
Hum... I should keep updatecli/updatecli.d/charts/rating.yaml though no?

**Comment by dduportal** [comment]
> Hum... I should keep updatecli/updatecli.d/charts/rating.yaml though no?


My apologies, I don't why I tought the manifest here was tracking the docker image for rating, while it's the helm chart.

You are correct: this PR is legit!

**Pull request closed without merging**
