### PR TITLE
chore(infra.ci.jenkins.io): move `helm-charts` job from `Kubernetes Management` folder to `Dependencies Management`

### PR DESCRIPTION
**Pull request by lemeurherve**
This PR moves this job which is only running updatecli.

We don't really care about build history for this job.

If it was the case, it would have needed to create the new job first, then connect into the controller and manually move the build history to this new job, then delete the old job.

### CODE REVIEW

**Review by dduportal — APPROVED** [review]
LGTM 👍 

Note: this will delete the build history, but we do not care for this job

**Comment by dduportal** [comment]
Note: this caused unexpected wave of unwanted updatecli PRs. See https://github.com/jenkins-infra/helm-charts/pull/797 and https://github.com/jenkins-infra/kubernetes-management/pull/4422

**Comment by hervelemeur** [comment]
@dduportal I've looked at the links but didn't see anything particular, how is it related to the updatecli wave?

**Comment by dduportal** [comment]
> @dduportal I've looked at the links but didn't see anything particular, how is it related to the updatecli wave?

By moving (e.g. deleting + creating) without the build history, the new job rebuilt the last tags (the <3 days old) which opened way more PRs than expected.

**Pull request merged**
