### PR TITLE
chore(accountapp): remove default `image.pullPolicy`

### PR DESCRIPTION
**Pull request by lemeurherve**
`IfNotPresent` is already the default value: https://kubernetes.io/docs/concepts/containers/images/#imagepullpolicy-defaulting

Supersedes and closes https://github.com/jenkins-infra/kubernetes-management/pull/4249

### CODE REVIEW

**Review by dduportal — CHANGES_REQUESTED** [review]
Alas it does not work as you would expect due to the chart being buggy: https://github.com/jenkins-infra/helm-charts/blob/2aff68e63375846a9942f8ff556d70b4a6e60f9c/charts/accountapp/templates/deployment.yaml#L29 

(The helmfile diff shows that the key is still specified but its value is undefined, which does not behave as described in the kube doc).


=> you might want to check the `helmfile diff` when doing such a change, before opening the PR to catch this kind of trick earlier

**Comment by dduportal** [comment]
For info, blocked by https://github.com/jenkins-infra/helm-charts/pull/593 which should solve the issue in a proper way

**Comment by lemeurherve** [comment]
Chart fixed in https://github.com/jenkins-infra/helm-charts/pull/593, released: https://github.com/jenkins-infra/helm-charts/releases/tag/accountapp-0.6.0

**Review by dduportal — APPROVED** [review]
LGTM, helmfile diff is 👍

**Pull request merged**
