### PR TITLE
Add an updatecli manifest to keep mirrorbits httpd docker digest up to date

### PR DESCRIPTION
**Pull request by karthikmurali60**
### Description

This PR adds an updatecli manifest to keep the docker digest of httpd docker image up to date

Issue - https://github.com/jenkins-infra/kubernetes-management/issues/4212

### CODE REVIEW

**Comment by karthikmurali60** [comment]
@lemeurherve can you please review this PR when you get a chance ?

**Comment by lemeurherve** [comment]
@karthikmurali60 thanks for the pull request!

I've triggered a build but it failed:
>  ERROR: ✗ unable to retrieve image docker-library/httpd:latest: GET https://index.docker.io/v2/docker-library/httpd/manifests/latest: UNAUTHORIZED: authentication required; [map[Action:pull Class: Name:docker-library/httpd Type:repository]]

I've looked in our other manifests with `dockerdigest` but all of them concern images in our `jenkinsciinfra` docker org, not any external one (not sure if it's related).

Suggestion: try with the image "http" instead of "docker-library/httpd"

**Comment by karthikmurali60** [comment]
@lemeurherve I think the issue is because the DockerHub authentication is failing. The error logs indicate its an unauthorized request to pull the docker digest. Can you please try to run the manifest by providing the appropriate credentials for DockerHub? We might get more information then to further debug the issue.

**Comment by lemeurherve** [comment]
Updatecli shouldn't need any additional credential, cf https://github.com/jenkins-infra/helm-charts/blob/main/updatecli/updatecli.d/mirrorbits.yaml#L24-L32 (note the use of `httpd` only as docker repository)

Looking at this, I realize the issue #4212 isn't needed, but instead the `httpd` tag should be removed from mirrorbits values at https://github.com/jenkins-infra/kubernetes-management/blob/d65ba387616155b588505174dd6a6a42f0a58986/config/mirrorbits.yaml#L8-L9 as this tag is already kept up to date in the mirrorbits helm chart.

@karthikmurali60 would you like to make this change? If so, you can close this PR and open another one.

**Comment by karthikmurali60** [comment]
@lemeurherve got it, thanks for the explanation. I will close this PR and make the required change in another one

**Pull request closed without merging**
