### PR TITLE
fix: override docker-registry-secrets values to use `datadog` namespace only on doks-public

### PR DESCRIPTION
**Pull request by lemeurherve**
Not used, and release failed as there isn't any `jenkins-agents` namespace on this cluster.

### CODE REVIEW

**Comment by lemeurherve** [comment]
Good point. I've restored it but only on `datadog` namespace to fix its release on doks-public.
WDYT @dduportal?

**Comment by dduportal** [comment]
Error on `doks-public`:

```console
Error: Failed to fetch credentials for cluster "0ba3a1ff-4f80-46b8-be4b-19844d1c1dd7": cluster not found
```

I assume you are working on this cluster as well?

**Comment by lemeurherve** [comment]
I've made some tests applying helmfile locally, but I had to reauthenticate, I suspect the kubeconfig has changed with the node pool size, checking.

**Comment by dduportal** [comment]
> I've made some tests applying helmfile locally, but I had to reauthenticate, I suspect the kubeconfig has changed with the node pool size, checking.

The build https://infra.ci.jenkins.io/job/terraform-jobs/job/digitalocean/job/main/141/consoleFull (private URL) shows that it destroyed the formed cluster in favor of a new one (resulting in the obsolescence of the current `kubeconfig`).

**Comment by dduportal** [comment]
> > I've made some tests applying helmfile locally, but I had to reauthenticate, I suspect the kubeconfig has changed with the node pool size, checking.
> 
> The build https://infra.ci.jenkins.io/job/terraform-jobs/job/digitalocean/job/main/141/consoleFull (private URL) shows that it destroyed the formed cluster in favor of a new one (resulting in the obsolescence of the current `kubeconfig`).

Oh yeah: https://github.com/jenkins-infra/digitalocean/commit/54130fb9903ccce523bfff1d0a65ce0492afbc49#diff-d7ab5fe3b23d86d54f3f15ed4af3aa674e26a76708e5c2b41102bbb7034ff66fL21 .

I remember that the "main default" node_pool, when changed, results in the destruction of the cluster. I don't know if you can create a cluster in DO with an empty node pool and use a "secondary" one?

**Review by smerle33 — APPROVED** [review]
🚀

**Pull request merged**
